module RodauthPhlex
  autoload :View, "rodauth_phlex/view"

  module Views
    autoload :ChangePassword, "rodauth_phlex/views/change_password"
    autoload :CloseAccount, "rodauth_phlex/views/close_account"
    autoload :ConfirmPassword, "rodauth_phlex/views/confirm_password"
    autoload :CreateAccount, "rodauth_phlex/views/create_account"
    autoload :EmailAuth, "rodauth_phlex/views/email_auth"
    autoload :Login, "rodauth_phlex/views/login"
    autoload :Logout, "rodauth_phlex/views/logout"
    autoload :MultiPhaseLogin, "rodauth_phlex/views/multi_phase_login"
    autoload :OtpAuth, "rodauth_phlex/views/otp_auth"
    autoload :OtpDisable, "rodauth_phlex/views/otp_disable"
    autoload :OtpSetup, "rodauth_phlex/views/otp_setup"
    autoload :OtpUnlock, "rodauth_phlex/views/otp_unlock"
    autoload :OtpUnlockNotAvailable, "rodauth_phlex/views/otp_unlock_not_available"
    autoload :RecoveryAuth, "rodauth_phlex/views/recovery_auth"
    autoload :Remember, "rodauth_phlex/views/remember"
    autoload :ResetPassword, "rodauth_phlex/views/reset_password"
    autoload :ResetPasswordRequest, "rodauth_phlex/views/reset_password_request"
    autoload :SmsAuth, "rodauth_phlex/views/sms_auth"
    autoload :SmsConfirm, "rodauth_phlex/views/sms_confirm"
    autoload :SmsDisable, "rodauth_phlex/views/sms_disable"
    autoload :SmsRequest, "rodauth_phlex/views/sms_request"
    autoload :SmsSetup, "rodauth_phlex/views/sms_setup"
    autoload :TwoFactorAuth, "rodauth_phlex/views/two_factor_auth"
    autoload :TwoFactorDisable, "rodauth_phlex/views/two_factor_disable"
    autoload :TwoFactorManage, "rodauth_phlex/views/two_factor_manage"
    autoload :UnlockAccount, "rodauth_phlex/views/unlock_account"
    autoload :UnlockAccountRequest, "rodauth_phlex/views/unlock_account_request"
    autoload :VerifyAccount, "rodauth_phlex/views/verify_account"
    autoload :VerifyAccountResend, "rodauth_phlex/views/verify_account_resend"
    autoload :VerifyLoginChange, "rodauth_phlex/views/verify_login_change"
    autoload :WebauthnAuth, "rodauth_phlex/views/webauthn_auth"
    autoload :WebauthnRemove, "rodauth_phlex/views/webauthn_remove"
    autoload :WebauthnSetup, "rodauth_phlex/views/webauthn_setup"
  end
end
